name: Modal Auto Deploy

# -----------------------------------------------------------------
# 唯一需要修改的地方：取消注释你需要部署的那一行即可
# -----------------------------------------------------------------
env:
  # DEPLOY_FILE: "comfyui-wan22-5b.py"
  # DEPLOY_FILE: "app.py"
  # DEPLOY_FILE: "llama.py"
  DEPLOY_FILE: "vllm-qwen3-8b-awq.py"
  # DEPLOY_FILE: "llama-Qwen3-14B-Q5-gguf.py"
  # DEPLOY_FILE: "llama-Qwen35-27B-WebNovelWriter-Q4-gguf.py"

# -----------------------------------------------------------------

on:
  push:
    branches:
      - main
    paths:
      # 动态引用上面开启的 DEPLOY_FILE 变量
      - "${{ env.DEPLOY_FILE }}"

  workflow_dispatch: # 网页端手动触发

jobs:
  deploy:
    name: Deploy to Modal
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      # MODAL_ENVIRONMENT: production 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Modal Client
        run: |
          python -m pip install --upgrade pip
          pip install modal

      - name: Deploy Modal App
        run: |
          # 动态执行上方选中的文件
          modal deploy "${{ env.DEPLOY_FILE }}"
